sudo: true
language: node_js
node_js:
- lts/*
- '10'
script:
- npm run report
after_script:
- npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
before_deploy:
- mkdir ./deploy && cp ./README.md ./deploy
deploy:
  provider: s3
  access_key_id:
    secure: pnsfG1zsGt4nmaO41D0TrNZmbOhfe5DnDZzhivuvgVN10dXdyyvUK8a6+/Q0TXwcK2U3AAXoFvKC26AaQTX/tngqyJZN1l10sxKEKcS1Nweo1IB9qPaQP//gKA7T5lzFMym1KFaTMArfAemB1dZYA/aWWW6u1Ukr8BXCNTI1eeWL+n6tAmXB9k/0UWJanGRaTykpINAGb0Zq0qzJGpjf+d8R0lXwwKc0s1EANjWk5XUOQfdRVIpOV/7Il+F9vEUXKFhrYZvlSeZMG1sE5E//+WrnDLPSWPob4/56SUhQZZWZsp/HCdjPUtY9XPDwVfyrGVGrtH6TjwIMuQOeo13RWPc/ODYw8Zk38ZQzvs9hjDc2PLQkftTTDk01kV/Dv/z6Bkzy1O70OcbTMTn9//hXwvE+hi2cRMeHCyrSbi1KTziozoliFiJMPpzX14NO83VamiybGd7bovxpRVWx5Rg9RbLbyAlksWSaft+DBvZR1USRLSJYCENZ+3wKBTczKZeMFZznfETx0BplpJvzqbTWggQTquuRP6E1mUkc4ATAc0XQq6+x5kCwH5f+f13nG5vqM5UBliEkACf3xMtAuR1C/5GfTtXwsCr7xOeLHSpPSRWzXPvJHNI9PJN17lur2dvam5AY2z2gH/Uur0ybGfNqZSumV0gsylOCBwdmd8fHYHg=
  secret_access_key:
    secure: lUmZDtl/RHwjCyiYoZkvk2He5bgMxm/1gIDxvtdkRAY4FU7H/YOXbKDI3WNQYlPFRlP3HLX74HjTWenyFRH4UQJDHOaHkq88+xy8YESgawD0Jgqep2ptPc4cC2cMeceLG3zgjT7j13Z2Th//d3jza1AWoEIl/TgxAsoMpdoVOa9rGnePZfPeG8cpiiTFkkCe/TCXXEkeDD4w3uIk03wFvXprSS1aAJFbrWbbwnHskAxaPFYnt8f4BZaooqQl83d4sLp/fY5N4RGA6sa8eWkDTtBacId66mwb5CkevxmJwsuGfeb4YVpq1GC+ji71gVPGPAXd+uirfAyJFiZNCcvkfGXF8QYQJMGx7lHMd9pF0twhGCV71DLf2NSujiXdiMywgNI6CzUrOvS+mvJtFQLzaz/tpZm7yIoXYLlsySlvmr7NVew5kNgWeArB/NXRBWjDVSXP+D0dveKuO/8dixhwJHa+UAI8KC5fU4+3i4QPxE0SptJ3cYcJy5j2xY1U4pp8Nx/CvMZlg61tJC4qDHSHVBA1KSPVzXjx6zobzlJIWStUhwFZlUaVEe/QC0ey6kQz3TYH+ZHhftlVKB+PqD6jhyJ9NPbfjABVklWVjM/euieXb88/Jvuk0j0NJH3X4TUiEfbgDsUOWFzM46ftgVaHJSQD5SEO43bhN3ycyFOmbVU=
  bucket: okanjo-docs
  skip_cleanup: true
  upload-dir: okanjo-app-td
  acl: public_read
  detect_encoding: true
  default_text_charset: utf-8
  local_dir: deploy
  on:
    branch: master
    repo: Okanjo/okanjo-app-td
